<?php
use Migrations\AbstractSeed;

/**
 * Courses seed.
 */
class CoursesSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['name' => 'Biologia marinha', 'monthly_amount' => '655', 'registration_tax' => '18', 'period' => 'afternoon', 'duration' => 31, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Biomedicina', 'monthly_amount' => '887', 'registration_tax' => '17', 'period' => 'morning', 'duration' => 7, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Botânica', 'monthly_amount' => '149', 'registration_tax' => '55', 'period' => 'night', 'duration' => 9, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Ciências Ambientais', 'monthly_amount' => '902', 'registration_tax' => '70', 'period' => 'night', 'duration' => 7, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Ciências da Saúde', 'monthly_amount' => '854', 'registration_tax' => '73', 'period' => 'night', 'duration' => 13, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Ciências do Meio Aquático', 'monthly_amount' => '394', 'registration_tax' => '51', 'period' => 'morning', 'duration' => 28, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Ecologia', 'monthly_amount' => '159', 'registration_tax' => '36', 'period' => 'night', 'duration' => 11, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Enfermagem', 'monthly_amount' => '990', 'registration_tax' => '77', 'period' => 'night', 'duration' => 35, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Fisioterapia', 'monthly_amount' => '588', 'registration_tax' => '96', 'period' => 'night', 'duration' => 20, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Fonoaudiologia', 'monthly_amount' => '132', 'registration_tax' => '67', 'period' => 'night', 'duration' => 24, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Gerontologia', 'monthly_amount' => '352', 'registration_tax' => '12', 'period' => 'afternoon', 'duration' => 34, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Meteorologia', 'monthly_amount' => '623', 'registration_tax' => '23', 'period' => 'afternoon', 'duration' => 9, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Microbiologia e Imunologia', 'monthly_amount' => '844', 'registration_tax' => '55', 'period' => 'morning', 'duration' => 9, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Naturologia', 'monthly_amount' => '939', 'registration_tax' => '40', 'period' => 'afternoon', 'duration' => 5, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Neurociência', 'monthly_amount' => '380', 'registration_tax' => '74', 'period' => 'afternoon', 'duration' => 22, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Quiropraxia', 'monthly_amount' => '538', 'registration_tax' => '56', 'period' => 'morning', 'duration' => 21, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Saúde Coletiva', 'monthly_amount' => '791', 'registration_tax' => '23', 'period' => 'night', 'duration' => 29, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Terapia ocupacional', 'monthly_amount' => '766', 'registration_tax' => '30', 'period' => 'afternoon', 'duration' => 11, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Aquacultura', 'monthly_amount' => '550', 'registration_tax' => '43', 'period' => 'morning', 'duration' => 22, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Cafeicultura', 'monthly_amount' => '849', 'registration_tax' => '77', 'period' => 'afternoon', 'duration' => 1, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Biotecnologia', 'monthly_amount' => '174', 'registration_tax' => '43', 'period' => 'morning', 'duration' => 1, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Ciência dos Alimentos', 'monthly_amount' => '693', 'registration_tax' => '84', 'period' => 'morning', 'duration' => 18, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Cosmetologia', 'monthly_amount' => '998', 'registration_tax' => '38', 'period' => 'night', 'duration' => 29, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Drenagem e Irrigação', 'monthly_amount' => '712', 'registration_tax' => '65', 'period' => 'morning', 'duration' => 13, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Enologia', 'monthly_amount' => '408', 'registration_tax' => '73', 'period' => 'afternoon', 'duration' => 31, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Fruticultura', 'monthly_amount' => '290', 'registration_tax' => '46', 'period' => 'night', 'duration' => 14, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Gestão de Recursos Hídricos', 'monthly_amount' => '615', 'registration_tax' => '19', 'period' => 'morning', 'duration' => 16, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Horticultura', 'monthly_amount' => '953', 'registration_tax' => '26', 'period' => 'morning', 'duration' => 6, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Meliponicultura', 'monthly_amount' => '817', 'registration_tax' => '23', 'period' => 'morning', 'duration' => 24, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Oftálmica', 'monthly_amount' => '782', 'registration_tax' => '59', 'period' => 'afternoon', 'duration' => 33, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Radiologia', 'monthly_amount' => '934', 'registration_tax' => '58', 'period' => 'afternoon', 'duration' => 35, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Silvicultura', 'monthly_amount' => '711', 'registration_tax' => '90', 'period' => 'night', 'duration' => 12, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Sistemas Biomédicos', 'monthly_amount' => '401', 'registration_tax' => '82', 'period' => 'afternoon', 'duration' => 33, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Astronomia', 'monthly_amount' => '568', 'registration_tax' => '47', 'period' => 'morning', 'duration' => 15, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Bioengenharia', 'monthly_amount' => '145', 'registration_tax' => '52', 'period' => 'night', 'duration' => 8, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Biofísica', 'monthly_amount' => '901', 'registration_tax' => '27', 'period' => 'morning', 'duration' => 33, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Ciências Contábeis', 'monthly_amount' => '970', 'registration_tax' => '82', 'period' => 'night', 'duration' => 35, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Ciência da Computação', 'monthly_amount' => '152', 'registration_tax' => '73', 'period' => 'morning', 'duration' => 21, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Ciências Biomoleculares', 'monthly_amount' => '327', 'registration_tax' => '80', 'period' => 'morning', 'duration' => 32, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Ciências Matemáticas da Terra', 'monthly_amount' => '966', 'registration_tax' => '38', 'period' => 'morning', 'duration' => 14, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Ciência & Tecnologia', 'monthly_amount' => '681', 'registration_tax' => '47', 'period' => 'afternoon', 'duration' => 18, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Engenharia Agrícola', 'monthly_amount' => '771', 'registration_tax' => '51', 'period' => 'afternoon', 'duration' => 25, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Engenharia Ambiental', 'monthly_amount' => '838', 'registration_tax' => '31', 'period' => 'night', 'duration' => 24, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Engenharia biomédica', 'monthly_amount' => '122', 'registration_tax' => '78', 'period' => 'morning', 'duration' => 12, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Engenharia de controle e automação', 'monthly_amount' => '443', 'registration_tax' => '83', 'period' => 'night', 'duration' => 18, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Engenharia Física', 'monthly_amount' => '185', 'registration_tax' => '91', 'period' => 'night', 'duration' => 7, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Engenharia geológica', 'monthly_amount' => '480', 'registration_tax' => '31', 'period' => 'morning', 'duration' => 30, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Engenharia Industrial Madeireira', 'monthly_amount' => '574', 'registration_tax' => '69', 'period' => 'night', 'duration' => 20, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Engenharia de Materiais', 'monthly_amount' => '214', 'registration_tax' => '70', 'period' => 'afternoon', 'duration' => 7, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Engenharia Mecatrônica', 'monthly_amount' => '546', 'registration_tax' => '75', 'period' => 'afternoon', 'duration' => 17, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Engenharia Metalúrgica', 'monthly_amount' => '681', 'registration_tax' => '58', 'period' => 'night', 'duration' => 35, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Engenharia Militar', 'monthly_amount' => '982', 'registration_tax' => '86', 'period' => 'afternoon', 'duration' => 7, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Engenharia de Minas', 'monthly_amount' => '652', 'registration_tax' => '20', 'period' => 'morning', 'duration' => 31, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Engenharia Naval e Oceânica', 'monthly_amount' => '420', 'registration_tax' => '64', 'period' => 'morning', 'duration' => 36, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Engenharia Nuclear', 'monthly_amount' => '220', 'registration_tax' => '35', 'period' => 'morning', 'duration' => 34, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Engenharia de Petróleo', 'monthly_amount' => '196', 'registration_tax' => '65', 'period' => 'night', 'duration' => 34, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Engenharia Sanitária', 'monthly_amount' => '533', 'registration_tax' => '95', 'period' => 'morning', 'duration' => 22, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Engenharia de Sistemas Eletrônicos', 'monthly_amount' => '643', 'registration_tax' => '30', 'period' => 'afternoon', 'duration' => 3, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Engenharia de Software', 'monthly_amount' => '958', 'registration_tax' => '94', 'period' => 'night', 'duration' => 21, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Engenharia de Tecidos', 'monthly_amount' => '921', 'registration_tax' => '43', 'period' => 'afternoon', 'duration' => 18, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Engenharia de Telecomunicações', 'monthly_amount' => '731', 'registration_tax' => '81', 'period' => 'night', 'duration' => 29, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Engenharia Têxtil', 'monthly_amount' => '781', 'registration_tax' => '83', 'period' => 'night', 'duration' => 36, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Física computacional', 'monthly_amount' => '301', 'registration_tax' => '72', 'period' => 'night', 'duration' => 17, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Física médica', 'monthly_amount' => '824', 'registration_tax' => '84', 'period' => 'night', 'duration' => 18, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Geofísica', 'monthly_amount' => '582', 'registration_tax' => '83', 'period' => 'morning', 'duration' => 24, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Geoprocessamento e Sensoriamento Remoto', 'monthly_amount' => '444', 'registration_tax' => '73', 'period' => 'afternoon', 'duration' => 35, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Informática biomédica', 'monthly_amount' => '449', 'registration_tax' => '77', 'period' => 'morning', 'duration' => 21, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Matemática Aplicada', 'monthly_amount' => '271', 'registration_tax' => '68', 'period' => 'afternoon', 'duration' => 11, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Matemática computacional', 'monthly_amount' => '391', 'registration_tax' => '22', 'period' => 'night', 'duration' => 2, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Nanotecnologia', 'monthly_amount' => '773', 'registration_tax' => '13', 'period' => 'night', 'duration' => 1, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Química ambiental', 'monthly_amount' => '884', 'registration_tax' => '47', 'period' => 'night', 'duration' => 32, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Química industrial', 'monthly_amount' => '245', 'registration_tax' => '65', 'period' => 'night', 'duration' => 3, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Sistemas de Informação', 'monthly_amount' => '693', 'registration_tax' => '41', 'period' => 'afternoon', 'duration' => 13, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Agrimensura', 'monthly_amount' => '662', 'registration_tax' => '48', 'period' => 'afternoon', 'duration' => 20, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Agroindústria', 'monthly_amount' => '597', 'registration_tax' => '87', 'period' => 'afternoon', 'duration' => 3, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Automação Industrial', 'monthly_amount' => '141', 'registration_tax' => '35', 'period' => 'morning', 'duration' => 8, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Biocombustíveis', 'monthly_amount' => '285', 'registration_tax' => '50', 'period' => 'afternoon', 'duration' => 36, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Ciências Aeronáuticas', 'monthly_amount' => '652', 'registration_tax' => '81', 'period' => 'morning', 'duration' => 23, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Ciência dos materiais', 'monthly_amount' => '471', 'registration_tax' => '69', 'period' => 'morning', 'duration' => 22, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Ciências Náuticas', 'monthly_amount' => '645', 'registration_tax' => '60', 'period' => 'afternoon', 'duration' => 13, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Construção de Edifícios', 'monthly_amount' => '248', 'registration_tax' => '49', 'period' => 'afternoon', 'duration' => 7, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Construção de Estradas', 'monthly_amount' => '970', 'registration_tax' => '97', 'period' => 'afternoon', 'duration' => 10, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Construção Naval', 'monthly_amount' => '599', 'registration_tax' => '36', 'period' => 'night', 'duration' => 32, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Energias Renováveis', 'monthly_amount' => '114', 'registration_tax' => '89', 'period' => 'night', 'duration' => 28, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Gestão da Tecnologia da Informação', 'monthly_amount' => '308', 'registration_tax' => '46', 'period' => 'afternoon', 'duration' => 6, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Gestão de Petróleo e Gás', 'monthly_amount' => '846', 'registration_tax' => '37', 'period' => 'morning', 'duration' => 36, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Gestão Portuária', 'monthly_amount' => '480', 'registration_tax' => '68', 'period' => 'afternoon', 'duration' => 18, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Manutenção Industrial', 'monthly_amount' => '153', 'registration_tax' => '49', 'period' => 'morning', 'duration' => 32, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Mecatrônica e Mecânica de Precisão', 'monthly_amount' => '536', 'registration_tax' => '49', 'period' => 'afternoon', 'duration' => 25, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Mineração', 'monthly_amount' => '957', 'registration_tax' => '62', 'period' => 'afternoon', 'duration' => 28, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Processos Metalúrgicos', 'monthly_amount' => '256', 'registration_tax' => '73', 'period' => 'morning', 'duration' => 16, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Processamento de Dados', 'monthly_amount' => '907', 'registration_tax' => '80', 'period' => 'morning', 'duration' => 33, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Produção de Laticínios', 'monthly_amount' => '114', 'registration_tax' => '32', 'period' => 'morning', 'duration' => 27, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Produção de Materiais Plásticos', 'monthly_amount' => '289', 'registration_tax' => '88', 'period' => 'morning', 'duration' => 35, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Produção Têxtil', 'monthly_amount' => '430', 'registration_tax' => '65', 'period' => 'morning', 'duration' => 26, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Produção Sucroalcooeira', 'monthly_amount' => '115', 'registration_tax' => '69', 'period' => 'afternoon', 'duration' => 0, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Redes de Computadores', 'monthly_amount' => '554', 'registration_tax' => '59', 'period' => 'morning', 'duration' => 0, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Redes de Telecomunicações', 'monthly_amount' => '786', 'registration_tax' => '92', 'period' => 'morning', 'duration' => 36, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Saneamento Ambiental', 'monthly_amount' => '517', 'registration_tax' => '53', 'period' => 'morning', 'duration' => 5, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Segurança da Informação', 'monthly_amount' => '610', 'registration_tax' => '37', 'period' => 'night', 'duration' => 28, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Sistemas Biomédicos', 'monthly_amount' => '274', 'registration_tax' => '18', 'period' => 'afternoon', 'duration' => 4, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Sistemas Elétricos', 'monthly_amount' => '646', 'registration_tax' => '94', 'period' => 'afternoon', 'duration' => 18, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Sistemas Embarcados', 'monthly_amount' => '283', 'registration_tax' => '49', 'period' => 'night', 'duration' => 9, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Sistemas de Navegação Fluvial', 'monthly_amount' => '866', 'registration_tax' => '76', 'period' => 'night', 'duration' => 33, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Sistemas para Internet', 'monthly_amount' => '969', 'registration_tax' => '95', 'period' => 'night', 'duration' => 6, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Telemática', 'monthly_amount' => '379', 'registration_tax' => '99', 'period' => 'night', 'duration' => 16, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Administração', 'monthly_amount' => '945', 'registration_tax' => '39', 'period' => 'night', 'duration' => 1, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Antropologia', 'monthly_amount' => '736', 'registration_tax' => '77', 'period' => 'night', 'duration' => 5, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Arqueologia', 'monthly_amount' => '597', 'registration_tax' => '66', 'period' => 'night', 'duration' => 24, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Arquitetura', 'monthly_amount' => '266', 'registration_tax' => '65', 'period' => 'night', 'duration' => 19, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Arquivística', 'monthly_amount' => '824', 'registration_tax' => '58', 'period' => 'afternoon', 'duration' => 5, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Artes Cênicas', 'monthly_amount' => '292', 'registration_tax' => '22', 'period' => 'afternoon', 'duration' => 32, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Artes Visuais', 'monthly_amount' => '994', 'registration_tax' => '81', 'period' => 'morning', 'duration' => 21, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Biblioteconomia', 'monthly_amount' => '331', 'registration_tax' => '43', 'period' => 'afternoon', 'duration' => 32, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Ciências Atuariais', 'monthly_amount' => '279', 'registration_tax' => '49', 'period' => 'morning', 'duration' => 30, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Ciências Sociais Licenciatura', 'monthly_amount' => '394', 'registration_tax' => '63', 'period' => 'afternoon', 'duration' => 14, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Cinema', 'monthly_amount' => '368', 'registration_tax' => '57', 'period' => 'afternoon', 'duration' => 3, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Comunicação social', 'monthly_amount' => '121', 'registration_tax' => '36', 'period' => 'afternoon', 'duration' => 36, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Desenho Industrial', 'monthly_amount' => '161', 'registration_tax' => '25', 'period' => 'afternoon', 'duration' => 31, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Design de Interiores', 'monthly_amount' => '634', 'registration_tax' => '32', 'period' => 'morning', 'duration' => 2, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Design de Moda', 'monthly_amount' => '516', 'registration_tax' => '88', 'period' => 'morning', 'duration' => 31, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Economia', 'monthly_amount' => '608', 'registration_tax' => '68', 'period' => 'afternoon', 'duration' => 18, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Economia Doméstica', 'monthly_amount' => '558', 'registration_tax' => '82', 'period' => 'morning', 'duration' => 27, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Editoração', 'monthly_amount' => '363', 'registration_tax' => '66', 'period' => 'morning', 'duration' => 25, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Escultura', 'monthly_amount' => '993', 'registration_tax' => '28', 'period' => 'night', 'duration' => 2, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Gastronomia', 'monthly_amount' => '107', 'registration_tax' => '87', 'period' => 'night', 'duration' => 21, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Gestão Ambiental', 'monthly_amount' => '569', 'registration_tax' => '37', 'period' => 'morning', 'duration' => 26, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Gestão Pública', 'monthly_amount' => '866', 'registration_tax' => '64', 'period' => 'night', 'duration' => 19, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Gravurismo', 'monthly_amount' => '242', 'registration_tax' => '89', 'period' => 'afternoon', 'duration' => 31, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'História da Arte', 'monthly_amount' => '778', 'registration_tax' => '11', 'period' => 'night', 'duration' => 6, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Hotelaria', 'monthly_amount' => '703', 'registration_tax' => '36', 'period' => 'afternoon', 'duration' => 12, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Museologia', 'monthly_amount' => '990', 'registration_tax' => '33', 'period' => 'night', 'duration' => 26, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Ordenamento do Território', 'monthly_amount' => '568', 'registration_tax' => '86', 'period' => 'afternoon', 'duration' => 31, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Paisagismo', 'monthly_amount' => '305', 'registration_tax' => '86', 'period' => 'night', 'duration' => 22, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Pintura', 'monthly_amount' => '852', 'registration_tax' => '25', 'period' => 'afternoon', 'duration' => 19, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Psicologia', 'monthly_amount' => '264', 'registration_tax' => '24', 'period' => 'morning', 'duration' => 23, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Publicidade & Propaganda', 'monthly_amount' => '807', 'registration_tax' => '16', 'period' => 'morning', 'duration' => 16, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Produção Cultural', 'monthly_amount' => '591', 'registration_tax' => '97', 'period' => 'night', 'duration' => 13, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Relações Internacionais', 'monthly_amount' => '162', 'registration_tax' => '56', 'period' => 'night', 'duration' => 14, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Relações Públicas', 'monthly_amount' => '183', 'registration_tax' => '38', 'period' => 'afternoon', 'duration' => 9, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Segurança Pública', 'monthly_amount' => '173', 'registration_tax' => '18', 'period' => 'morning', 'duration' => 2, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Serviço Social', 'monthly_amount' => '102', 'registration_tax' => '38', 'period' => 'night', 'duration' => 4, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Transporte Terrestre', 'monthly_amount' => '617', 'registration_tax' => '20', 'period' => 'night', 'duration' => 30, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Turismologia', 'monthly_amount' => '510', 'registration_tax' => '21', 'period' => 'afternoon', 'duration' => 29, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Urbanismo', 'monthly_amount' => '279', 'registration_tax' => '88', 'period' => 'night', 'duration' => 7, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Agroecologia', 'monthly_amount' => '513', 'registration_tax' => '68', 'period' => 'morning', 'duration' => 19, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Comércio Exterior', 'monthly_amount' => '684', 'registration_tax' => '56', 'period' => 'morning', 'duration' => 19, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Cooperativismo', 'monthly_amount' => '284', 'registration_tax' => '24', 'period' => 'morning', 'duration' => 25, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Design de Jogos Digitais', 'monthly_amount' => '648', 'registration_tax' => '26', 'period' => 'afternoon', 'duration' => 28, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Design de produto', 'monthly_amount' => '206', 'registration_tax' => '38', 'period' => 'afternoon', 'duration' => 29, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Design gráfico', 'monthly_amount' => '575', 'registration_tax' => '60', 'period' => 'night', 'duration' => 22, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Eventos', 'monthly_amount' => '215', 'registration_tax' => '79', 'period' => 'morning', 'duration' => 1, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Esporte e Lazer', 'monthly_amount' => '444', 'registration_tax' => '89', 'period' => 'morning', 'duration' => 23, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Fotografia', 'monthly_amount' => '549', 'registration_tax' => '59', 'period' => 'night', 'duration' => 33, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Gestão do Agronegócio', 'monthly_amount' => '447', 'registration_tax' => '77', 'period' => 'morning', 'duration' => 1, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Gestão Comercial', 'monthly_amount' => '589', 'registration_tax' => '74', 'period' => 'morning', 'duration' => 3, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Gestão Financeira', 'monthly_amount' => '971', 'registration_tax' => '69', 'period' => 'afternoon', 'duration' => 12, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Gestão Hospitalar', 'monthly_amount' => '762', 'registration_tax' => '18', 'period' => 'afternoon', 'duration' => 6, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Gestão de Segurança Privada', 'monthly_amount' => '847', 'registration_tax' => '37', 'period' => 'night', 'duration' => 13, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Gestão da Qualidade', 'monthly_amount' => '551', 'registration_tax' => '68', 'period' => 'afternoon', 'duration' => 9, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Logística', 'monthly_amount' => '166', 'registration_tax' => '58', 'period' => 'morning', 'duration' => 28, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Mercadologia', 'monthly_amount' => '534', 'registration_tax' => '52', 'period' => 'afternoon', 'duration' => 10, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Negócios Imobiliários', 'monthly_amount' => '994', 'registration_tax' => '13', 'period' => 'afternoon', 'duration' => 23, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Processos Escolares', 'monthly_amount' => '829', 'registration_tax' => '60', 'period' => 'night', 'duration' => 20, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Produção Fonográfica', 'monthly_amount' => '624', 'registration_tax' => '90', 'period' => 'morning', 'duration' => 17, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Recursos Humanos', 'monthly_amount' => '880', 'registration_tax' => '83', 'period' => 'night', 'duration' => 2, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Secretariado', 'monthly_amount' => '902', 'registration_tax' => '88', 'period' => 'afternoon', 'duration' => 31, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Segurança no Trabalho', 'monthly_amount' => '362', 'registration_tax' => '80', 'period' => 'morning', 'duration' => 16, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
            ['name' => 'Transporte Aéreo', 'monthly_amount' => '562', 'registration_tax' => '56', 'period' => 'morning', 'duration' => 18, 'created' => date('Y-m-d H:i:s'), 'modified' => date('Y-m-d H:i:s')],
        ];

        $table = $this->table('courses');
        $table->insert($data)->save();
    }
}
